### PR TITLE
UI/ux

### PR DESCRIPTION
**Pull request by rcodyp**
fixing frontpage ui/ux for margin and border-radius for better interface(https://github.com/user-attachments/assets/e16a2a86-9a5c-4f98-ab8b-e0d99ae20633)

### CODE REVIEW

**Comment by cboltz** [comment]
You accidentally chose a wrong, two years old target branch. I just fixed that, which also makes the diff readable.

**Comment by hellcp** [comment]
I think we can go harder on this, let's increase both margin and border radius

**Comment by rcodyp** [comment]
(https://github.com/user-attachments/assets/57dff654-838c-44a5-b18a-45ab6139f479)
is it right or should be do more ?

**Comment by hellcp** [comment]
Nothing changed in the PR

**Pull request closed without merging**
