### PR TITLE
Fixes link redirection problem of Github

### PR DESCRIPTION
**Pull request by Priyankagarai**
closes https://github.com/openSUSE/get-o-o/issues/213

The github source link will now open in new tab. By using the target attribute in HTML I have solved the problem.

### CODE REVIEW

**Comment by lkocman** [comment]
@hellcp will you please look into this one?

**Comment by hellcp** [comment]
I mean, it modifies a result file and not a source file, so this can't be merged as is

**Comment by lkocman** [comment]
Merging. Thank you @hellcp

**Comment by hellcp** [comment]
What about "this can't be merged as is" qualifies for "Merging."

**Comment by lkocman** [comment]
Oh my! I totally read "can". Let me revert this. Thank you for catching @hellcp

**Pull request merged**
