### PR TITLE
Leap Micro 5.2 is RC today

### PR DESCRIPTION
**Pull request by lkocman**
Change layout to better explain our install media and images. Reference demo

overview
download

### CODE REVIEW

**Comment by lkocman** [comment]
The time on the screenshot was set to 01:00 UTC while the time in the PR is set to our typical release time later today.

**Review by hellcp — APPROVED** [review]

**Comment by grisu48** [comment]
I just want to say one minor thing:

THIS IS FREAKING AWESOME!!!! :partying_face: :tada: :beers:

**Review by ggardet — APPROVED** [review]
LGTM!

**Comment by lkocman** [comment]
Reviewed changes on the community meet-up. Thanks to everyone for co-operation!!!

**Pull request merged**
