### PR TITLE
- changed docs strings + URLs to match Leap vs Tumbleweed distinction…

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
… where relevant (NB: should be re-applied to all `_data/locales/{locale}.yml`; worth discussing probably)

- changed string "Checksums Help" to "Auth... + Int Checks"
- changed corresponding url to new docs which describes the procedure better

Signed-off-by: Nycticorax <mrnycticorax@gmail.com>

### CODE REVIEW

**Comment by hellcp** [comment]
It may be worth the effort to do:
```liquid
{% if include.distro == "Leap" %}
   <li>
    ...
  </li>
{% else %}
   <li>
    ...
  </li>
{% endif %}
```
Just so we don't display docs that aren't relevant to the page the person is visiting

**Comment by why-not-try-calmer** [comment]
> It may be worth the effort to do:
> 
> ```
> {% if include.distro == "Leap" %}
>    <li>
>     ...
>   </li>
> {% else %}
>    <li>
>     ...
>   </li>
> {% endif %}
> ```
> 
> Just so we don't display docs that aren't relevant to the page the person is visiting

Yes if I thought about something like this but I feel uneasy about it. The Leap vs Tumbleweed distinction does exist, but it is blurry or, better said, it's gerrymandered (Yast and Zypper work the same, but key aspects of the workflow differ, e.g. the way you update, the way you rollback, how you backup, etc. I think the best we can do for now if be transparent from the get go and not try to guess what branch of a conditional best fits the user's needs.

**Comment by hellcp** [comment]
Then don't label them as specifically Leap or Tumbleweed?

**Comment by why-not-try-calmer** [comment]
> Then don't label them as specifically Leap or Tumbleweed?

So to repeat:
- the distinction exists
- it's a Good Idea to treat different things differently, at least internally, because We Know Better
- it's a Good Idea to expose our different treatment of different things with a flat list, instead of hidings things under conditionals

**Pull request closed without merging**
