### PR TITLE
add leap_micro 5.3

### PR DESCRIPTION
**Pull request by lkocman**
Let's make quick Beta availability on top of SLE Micro 5.3 RC1

### CODE REVIEW

**Comment by lkocman** [comment]
5 3-beta-download-in-progress
micro-53-beta

**Comment by hellcp** [comment]
Where's 53.yml?

**Comment by lkocman** [comment]
Ah let me supply them @hellcp

**Comment by lkocman** [comment]
Of course uncommitted! my bad

**Pull request merged**
