### PR TITLE
Revert Minimal-VM to JeOS for now

### PR DESCRIPTION
**Pull request by vmoutoussamy**
After spotting download issue in https://github.com/openSUSE/get-o-o/pull/123

### CODE REVIEW

**Comment by hellcp** [comment]
This breaks Tumbleweed in this state

**Comment by vmoutoussamy** [comment]
oh? how? I have tested this locally without issue

**Comment by hellcp** [comment]
I mean that, in the future the jeos images will disappear for Tumbleweed, so we should keep minimal-vm ones instead of reverting them

**Comment by DimStar77** [comment]
> I mean that, in the future the jeos images will disappear for Tumbleweed, so we should keep minimal-vm ones instead of reverting them

The future is now - the kiwi-templates-JeOS package was deleted 2 days ago, which also resulted in the removal of the -JeOS flavors from the FTP tree: 
  https://download.opensuse.org/tumbleweed/appliances/?P=*JeOS*

**Review by lkocman — CHANGES_REQUESTED** [review]
Please keep the tumbleweed.yml

**Pull request merged**
