### PR TITLE
Add colour to the "Server" segment and add new backgrounds

### PR DESCRIPTION
**Pull request by lilfrogg**
The "Desktop" segment of get-o-o having both a coloured background and background image while the "Server" segment only has a plain black background looks very unfinished in my opinion. So I added some colour to it and added a new modified background image to both segments.

The previous wallpaper.jpg background seems needlessly huge(3mb) for a decorating background element and I think ideally it should be removed and replaced with something more efficient altogether. For now, I left it there and also left the orginal wallpaper-bg class intact as I didn't check whether it was used elsewhere on get-o-o.

Also, this is my very first commit and I'm very new to git and github. The commit history for this pull request is probably a bit unneccessarily messy, but I donÄ't really know how to fix that.

### CODE REVIEW

**Comment by lkocman** [comment]
Could you please upload a screenshot(s)? Thank you

**Comment by lilfrogg** [comment]
image

**Comment by lilfrogg** [comment]
This is one narrower resolutions/portrait mode for mobile
image

**Comment by lilfrogg** [comment]
This is on narrower resolutions, like portrait mode on phones:
image

**Comment by hellcp** [comment]
hm, did you maybe try replacing the background in the svg with black to see if it's better? I am not really sure if a wallpaper is the best way to represent the server either, but it's better than nothing

**Comment by lilfrogg** [comment]
Oh, so maybe the idea was to use the wallpaper for the desktop part because, well, it's the default desktop wallpaper and the server part was black because, well, it has no GUI? It is indeed a bit hard to find something that visually represents a server. The only things I could thing of would either be a (stylized) terminal prompt, but that might be a bit confusing visually or a stock image of a server, like this:

Screenshot from 2022-05-26 15-08-05

Although that might also not be super representative of the average use case of a oS server distribution.


I still think the way the wallpaper is used for decorative purpose in other places of the get page is not be ideal though and can look wildly different for different screen sized. Or at least the wallpaper should be cropped and downscaled a bit and converted into a gif for smaller file size imo. (I could also do that, of course)

**Comment by lkocman** [comment]
let's postpone it post tomorrow (Leap 15.4 GA. Otherwise I like the server bg, we could do a matching desktop as well
that would actually look quite cool. @hellcp any further thoughts?

**Comment by lilfrogg** [comment]
Ummm, I'm not sure what you mean here. What's an SR text and what issues were mentioned?

**Comment by lilfrogg** [comment]
It seems like by trying to revert my repository to bring it to the same state of the main one and trying to clean up my commit history, I have only created a bigger mess of commits. Should I just delete my repository and fork anew to start from a clean slate(there's a warning about this being a bad idea, so I'm not sure I'm aware of all the implications) or can you just cherrypick commits when accepting a pull request anyways, so that your repository won't be polluted by my nonsense.

**Comment by lilfrogg** [comment]
I cleaned up the commit history now and re-opened the request with only the new server background at the moment.

**Comment by lilfrogg** [comment]
I cleaned up the commit history now and re-opened the request with only the new server background at the moment.

**Comment by lilfrogg** [comment]
A couple mock ups for how a corresponding desktop section could look:
desktop1
desktop2
desktop3
desktop4

**Comment by lilfrogg** [comment]
Last one a bit more zoomed in
desktop5

**Comment by hellcp** [comment]
They feel a touch too busy compared to the server one

**Comment by lilfrogg** [comment]
Yeah, that's probably true. Not sure what good visual representation for a desktop could be that would blend into the background as well as the server. You could theoretically just darken the whole background a bit more (the second one would probably be best suited for that) or have it hyper zoomed in so you only see the edges of the screen. Not sure either of those would look super good either though. 
Or maybe just stick with the current wallpaper approach. Nothing wrong with that either.

(Two very quick mock-ups for the approaches mentioned)
desktop6
desktop7

**Comment by lilfrogg** [comment]
*ignore this*

**Pull request closed without merging**
