### PR TITLE
add localization support

### PR DESCRIPTION
**Pull request by guoyunhe**
I cannot build this site locally. Can @hellcp try?

### CODE REVIEW

**Comment by hellcp** [comment]
You need to run rake to build this site, as per instructions

**Comment by hellcp** [comment]
It takes a bit under 9 minutes to build the site with this patch, which is kinda annoying, but I assume that is kinda expected

**Comment by guoyunhe** [comment]
I don't know. For other sites with jekyll-locale, it only takes one or two seconds.

**Comment by guoyunhe** [comment]
I think it is because here is a lot of HTTP requests to get file sizes of ISOs on the server:

```
{% capture size %}{% filesize %}https://download.opensuse.org{{type.primary_link}}{% endfilesize %}{% endcapture %}
```

This should not be done in rendering process. `jekyll-locale` will render same page multiple times for different languages. But we only need to fetch the file size once.

**Comment by hellcp** [comment]
> This should not be done in rendering process. `jekyll-locale` will render same page multiple times for different languages. But we only need to fetch the file size once.

Yeah, I will rewrite it as a rake thing, it will be faster

**Comment by guoyunhe** [comment]
It can be directly saved into `_data/*.yml` files.

**Comment by hellcp** [comment]
I don't like that approach, when we did that in software-o-o, it was never updated, and the sizes were never correct

**Comment by hellcp** [comment]
Done, it finishes in under a second now

**Comment by guoyunhe** [comment]
The basic translation support is ready now. What you need to do next is replace strings in HTML:

```html
<h1>openSUSE Distributions</h1>
```

To:

```html
<h1>{{ locale.opensuse_distributions }}</h1>
```

And add new key into `_data/locales/en.yml`:

```yaml
opensuse_distributions: openSUSE Distributions
```

Then, you can write an email to weblate admins to add this repo to Weblate.

**Comment by hellcp** [comment]
Alright, thanks, this is mergeable now then

**Pull request merged**
