### PR TITLE
Add signature download, fix verification description (boo#1211156).

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by hramrach** [comment]
They are not causing problem, are they?

It's not like I would add this by hand, and the yaml generator considers the URLs too complex to leave them unquoted.

**Comment by tacerus** [comment]
They are not causing a problem for the YAML parsing unless YAML control characters standing alone are part of the strings, which does not seem to be the case.
I suggest to propose different YAML formatting as a separate patch.

**Comment by hramrach** [comment]
The different yaml formatting is a result of roundtrip through yaml parser/serializer adding the extra lines programatically in-between. It's not intentional change but so long as the result is usable I see no problem with it.

**Comment by hellcp** [comment]
It makes reviewing actual intended changes difficult, so I disagree it makes no difference

**Comment by hramrach** [comment]
The formatting change is now in a separate patch

**Comment by hramrach** [comment]
Looks good, thanks.

**Pull request merged**
