### PR TITLE
Add ppc64 download link for tumbleweed.

### PR DESCRIPTION
**Pull request by hramrach**
Fixes: #125
Signed-off-by: Michal Suchanek <msuchanek@suse.de>

### CODE REVIEW

**Comment by hramrach** [comment]
Do you want the translations as well?

**Comment by hellcp** [comment]
Translations will be populated by weblate later, I will leave the fate of this PR with Lubos, as he is probably more equipped to review things related to release management, and can raise any issues with the rest of the people there. I'm a bit surprised this is added in the primary Installation group though, is ppc64 considered a primary architecture port now?

**Comment by hramrach** [comment]
Is there a secondary installation group?

I don't think s390x is primary architecture for Tumbleweed either, nor is ppc64le.

**Comment by hellcp** [comment]
Not yet, nobody added it yet. s390x as far as I understand it was added in agreement with the release team though

**Comment by hramrach** [comment]
I don't care all that much about installation groups, I want a link that people looking for the medium will see.

**Comment by lkocman** [comment]
I shall not speak for TW. Let me ask @DimStar77

**Review by lkocman — APPROVED** [review]
In general I support anything that will result into users having "easier" way of accessing images.

**Pull request merged**
